org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false
org.gradle.daemon=true

mc_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_version=21.1.224
neo_version_range=[21.1.1,)
minecraft_version_range=[1.21.1,1.22)
kubejs_version=2101.7.1-build.181
rhino_version=2101.2.7-build.74

mod_id=idealland_shrine
mod_name=Idealland Shrine
mod_license=MIT
mod_version=1.2.0
mod_group_id=cn.mcmod.ideallandshrine
mod_authors=Polaris_Light
mod_description=Idealland shrine module for NeoForge 1.21.1.
